name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:

  print-message-job:
    runs-on: ubuntu-latest
    steps:

      - name: "printing step"
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."